//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2C2P_TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TransactionDATA
    {
        public long ID { get; set; }
        public string TRNID { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string CURRENCY { get; set; }
        public string TRANDATE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> UPLOADDTE { get; set; }
    }
}
